version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db_indra
      - POSTGRES_USER=parthkal
      - POSTGRES_PASSWORD=yolo1712

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
